### ISSUE TITLE
Open Cypress shortcut can't handle spaces in the filepath on Windows

### ISSUE THREAD

**Issue by edgewords** [90poe/vscode-cy-helper#34]
When you hover over an 'it' block and click the 'Open Cypress' shortcut, it executes the Open Cypress command I have defined, and then appends the filepath to the spec file. However, on Windows, if the file path contains spaces, it fails:

PS C:\Users\tom\Documents\Projects\Cypress Projects\CypressTraining> **npx cypress open --config testFiles=c:\Users\tom\Documents\Projects\Cypress Projects\CypressTraining\cypress\integration\exercises\sync.spec.js**

The Cypress Test Runner opens with an error that no files are found in the path

Is it possible to automatically surround the filepath with double quotes to allow for spaces in filepaths?

**Environment (please complete the following information):**
- Extension version:                              1.0.1
- VS Code version:                                1.52.1
- OS:                                                     Windows 10

**Comment by Shelex** [comment]
@edgewords Hello! Thank you for opening an issue.
Should be addressed in v1.0.2, could you please check on your side?

**Comment by edgewords** [comment]
Thanks Shelex, I have updated & I now get the quotes around the filepath: 

**npx cypress open --config testFiles="c:\Users\tom\Documents\Projects\Cypress Projects\CypressTraining\cypress\integration\exercises\firstTest.spec.js"**

**BUT** - still getting an error that no test files found. The error shows 
No Files Found in **C:\Users\tom\Documents\Projects\Cypress Projects\CypressTraining\cypress\integration**

So the path is not pointing to the full path to the **subfolder** & file, just to the integration folder, so not sure what's happening now?
![image](https://user-images.githubusercontent.com/35366513/106278648-fef09a80-6232-11eb-896d-2929c2e8e44a.png)

**Comment by edgewords** [comment]
Sorry @Shelex I just found how to turn on the **Run** command, and just tried it, but I get a file not found with this one as well:

![image](https://user-images.githubusercontent.com/35366513/106282809-06b33d80-6239-11eb-83a4-53b6d5d1d691.png)

**Comment by edgewords** [comment]
@Shelex I've been playing around with this, and the problem seems to be that --spec takes in a glob pattern, and as there is a space character in my filepath, it then sees this as two separate glob patterns (split on the space), so I don't think this is your extension, but a problem with windows paths with spaces & the glob pattern. As I have tried it manually with many different formats & it still gives an error.
Normally I don't see this, as I use the terminal in VS Code, so the path is just a relative path & I don't have the folder in the path with the space character.

**Comment by edgewords** [comment]
I have now removed the space in the folder name in the file path to check it is the glob pattern.
The **Open** shortcut now works!
But, the **Run** one doesn't for some reason
![image](https://user-images.githubusercontent.com/35366513/106298741-2e5fd100-624c-11eb-8be4-ce7b9ed508d7.png)

**Comment by Shelex** [comment]
> I have now removed the space in the folder name in the file path to check it is the glob pattern.
> The **Open** shortcut now works!
> But, the **Run** one doesn't for some reason
> ![image](https://user-images.githubusercontent.com/35366513/106298741-2e5fd100-624c-11eb-8be4-ce7b9ed508d7.png)
> 

I will try my windows laptop later to debug this properly, basic idea is to pass relative path to cypress instead of absolute, or wrap it in glob pattern, maybe that is a reason why it does not work well on windows.

**Comment by edgewords** [comment]
OK, now found the issue.
When I use your Run command, I get a filepath as follows:
npx cypress run --spec "c:\Users\tom\Documents\Projects\CypressProjects\CypressTraining\cypress\integration\exercises\firstTest.spec.js"

If I change the c:\ to C:\ (uppercase):
npx cypress run --spec "C:\Users\tom\Documents\Projects\CypressProjects\CypressTraining\cypress\integration\exercises\firstTest.spec.js"

Then it works!! So is it possible to make it upper? No idea why this would make a difference.

**Comment by Shelex** [comment]
@edgewords thank you for investigating.
Case sensitivity issue is ridiculous :)
Will check it also and agree that with relative path we could avoid more such issues.
